Add missing header for boost
Fixes the following error:

/src/tests/time_based_update_policy_test.cpp:71:5:   required from here
/usr/include/boost/optional/optional.hpp:1596:3: error: static assertion failed: If you want to output boost::optional, include header <boost/optional/optional_io.hpp>
 1596 |   BOOST_STATIC_ASSERT_MSG(sizeof(CharType) == 0, "If you want to output boost::optional, include header <boost/optional/optional_io.hpp>");
      |   ^~~~~~~~~~~~~~~~~~~~~~~
/usr/include/boost/optional/optional.hpp:1596:3: note: '(sizeof (char) == 0)' evaluates to false